import { docs } from "@/.source/server";
import { loader } from "fumadocs-core/source";

// The content source for the docs site. `docs` is generated by fumadocs-mdx
// into .source from the MDX files in content/docs (see source.config.ts).
export const source = loader({
  baseUrl: "/docs",
  source: docs.toFumadocsSource(),
});
