export const circuitFieldParams = {
  resolution: 1.5,
  fov: 23.5,
  dolly: 2.52,
  spacing: 0.75,
  rackSpeed: 0,
  aperture: 20.25,
  falloff: 1.1,
  minBlur: 0,
  count: 18,
  scaleMin: 0.82,
  scaleMax: 1.69,
  stroke: 3,
  curviness: 1,
  taper: 0.43,
  elbow: 1,
  elbowMid: 0.45,
  elbowRound: 49,
  breathe: 0,
  lifetime: 16.5,
  sweepSpeed: 1.95,
  band: 0.09,
  gapMult: 0,
  floor: 0,
  exposure: 0.25,
  atmosphere: 0.36,
  timeScale: 1.07,
  sweepDirection: "topToBottom",
  phaseMode: "depth",
  depthOrder: "farToNear",
  depthStagger: 1.5,
  sweepDuration: 13.75,
  sweepGap: 19.25,
  timingVariation: 0.02,
  wireFlow: 1,
  seedBase: 679207,
  bandC0: "#00f0a0",
  bandC1: "#ff6714",
  bandC2: "#bb00ff",
  bandMid: 0.07,
  tintC: "#0bf933",
  tintAmt: 0,
  tiltFrom: -42,
  tiltTo: 9,
  scrollBlur: 0,
  scrollDimTo: 0,
};

export const CIRCUIT_FIELD_CHOREOGRAPHY_PRESETS = {
  current: {
    rackSpeed: 0,
    aperture: 30,
    minBlur: 1.1,
    lifetime: 5,
    sweepSpeed: 1.84,
    band: 0.085,
    gapMult: 1.2,
    floor: 0.02,
    timeScale: 1.08,
    breathe: 0,
    exposure: 1.05,
    sweepDirection: "mixed",
    phaseMode: "random",
    depthOrder: "nearToFar",
    depthStagger: 0,
    sweepDuration: 10,
    sweepGap: 3,
    timingVariation: 1,
    wireFlow: 0,
  },
  depthCascade: {
    rackSpeed: 0,
    aperture: 20.25,
    minBlur: 0,
    lifetime: 16.5,
    sweepSpeed: 1.95,
    band: 0.09,
    gapMult: 0,
    floor: 0,
    timeScale: 1.07,
    breathe: 0,
    exposure: 0.25,
    sweepDirection: "topToBottom",
    phaseMode: "depth",
    depthOrder: "farToNear",
    depthStagger: 1.5,
    sweepDuration: 13.75,
    sweepGap: 19.25,
    timingVariation: 0.02,
    wireFlow: 1,
  },
} as const;

export type CircuitFieldChoreographyPreset =
  keyof typeof CIRCUIT_FIELD_CHOREOGRAPHY_PRESETS;

export const CIRCUIT_FIELD_TUNE_EVENT = "circuit-field-tune";
