export const circuitFieldParams = {
  resolution: 2,
  maxFps: 30,
  pauseWhenHidden: true,
  cacheGeometry: true,
  batchBlur: true,
  blurGroups: 4,
  fov: 45,
  dolly: 0.98,
  spacing: 0.34,
  rackSpeed: 0,
  aperture: 30,
  falloff: 2.7,
  minBlur: 3.7,
  count: 9,
  scaleMin: 2,
  scaleMax: 2.5,
  coverageMin: 1.2,
  coverageMax: 0.72,
  depthSizeCompensation: 0.64,
  stroke: 4,
  curviness: 1,
  taper: 0.75,
  elbow: 1,
  elbowMid: 0.81,
  elbowRound: 59,
  breathe: 0,
  lifetime: 11,
  sweepSpeed: 2.13,
  band: 0.05,
  gapMult: 1,
  floor: 0.25,
  exposure: 1.49,
  atmosphere: 0.7,
  timeScale: 1.19,
  sweepDirection: "topToBottom",
  phaseMode: "depth",
  depthOrder: "farToNear",
  depthStagger: 1.5,
  sweepDuration: 12.5,
  sweepGap: 0,
  edgePadding: 4.5,
  timingVariation: 0.2,
  wireFlow: 1,
  seedBase: 679207,
  bandC0: "#3700ff",
  bandC1: "#ff4000",
  bandC2: "#0ea503",
  bandMid: 0.3,
  tintC: "#0400ff",
  tintAmt: 0.17,
  tiltFrom: -62,
  tiltTo: -44,
  scrollBlur: 15,
  scrollDimTo: 0,
};

export const CIRCUIT_FIELD_CHOREOGRAPHY_PRESETS = {
  current: {
    rackSpeed: 0,
    aperture: 30,
    minBlur: 1.1,
    lifetime: 5,
    sweepSpeed: 1.84,
    band: 0.085,
    gapMult: 1.2,
    floor: 0.02,
    timeScale: 1.08,
    breathe: 0,
    exposure: 1.05,
    sweepDirection: "mixed",
    phaseMode: "random",
    depthOrder: "nearToFar",
    depthStagger: 0,
    sweepDuration: 10,
    sweepGap: 3,
    edgePadding: 5,
    timingVariation: 1,
    wireFlow: 0,
  },
  depthCascade: {
    rackSpeed: 0,
    aperture: 30,
    minBlur: 3.7,
    lifetime: 11,
    sweepSpeed: 2.13,
    band: 0.05,
    gapMult: 1,
    floor: 0.25,
    timeScale: 1.19,
    breathe: 0,
    exposure: 1.49,
    sweepDirection: "topToBottom",
    phaseMode: "depth",
    depthOrder: "farToNear",
    depthStagger: 1.5,
    sweepDuration: 12.5,
    sweepGap: 0,
    edgePadding: 4.5,
    timingVariation: 0.2,
    wireFlow: 1,
  },
} as const;

export type CircuitFieldChoreographyPreset =
  keyof typeof CIRCUIT_FIELD_CHOREOGRAPHY_PRESETS;

export const CIRCUIT_FIELD_TUNE_EVENT = "circuit-field-tune";
